### ISSUE TITLE
HEX file delete event impacts Windows GUI

### ISSUE THREAD

**Issue by Anobium** [MicrochipTech/XPRESS-Loader#2] opened 2016-03-19 11:05 UTC
The new release of the code operates differently to the shipped code on the XPress Board.

The latest purges the HEX file after downloading, whilst the original XPress Board code did retain the HEX file.  

There is an  issue relating to the event handling on a Windows 7 computer. After the file has been programmed, after some predetermined time, the HEX is delete this 'shudders' the operating system with the Xpress drive folder taking precedence on the screen.  It looks like a fast flicker every time you write a file.

If I use the original 18f code this 'shudder' does not happen.

What should I change in the source to remove the delete event?

**Comment by perkyguy** [comment] 2016-03-19 19:42
I believe this is more of issue with Windows rather than the board itself. However, I haven't been able to recreate this. What is your "Removal Policy" for the Xpress board? I believe this should be in the disk's properties, and then Policies tab.

**Comment by Anobium** [comment] 2016-03-20 08:22
Settings are the same.  I have put together a video of the issue.

Reconfirm condition:  Original 18f firmware, read from a shipped device, work ok.  When file is transfer to USB drive the file is retained and no shuddering of the system.  Newly compiled hex - file does get programmed but the file disappears (as it would if a reinsertion event had occurred).

Question: Is the code in GitHub exactly the same code base used for the shipped devices?

**Comment by perkyguy** [comment] 2016-03-21 16:23
I still am unable to reproduce this.

Where did you post the video? How long does it normally take to have the "shudder"? What is the removal policy for both of the drives? Does the button S1 get hit at all or does the voltage sag a little at all?

Functionally the code is exactly the same. Some commenting/formatting/slight refactoring happened, but otherwise the code is the same

**Comment by Anobium** [comment] 2016-03-21 16:30
See below. I only numbered for clarity - no other reason. :-)
1.   I can post the video to Dropbox.  Can you send me a GitHub personal message and  I will send you the  link.
2. The events related to the shuddering are when the file is placed in the USB drive.

3, Removal policy is the same.
1. S1 button is not hit.  This is occurring without S1 being hit.
2. Voltage sag? Can you explain please. I can measure.
3. There is difference that I thought of with respect the software.  Does the shipped board have a bootloader? If it does then can you let me have the bootloader and I will program that in.

**Comment by Anobium** [comment] 2016-03-21 17:25
I just figured out... no PM in Github so here is the link

URL Removed.

**Comment by Anobium** [comment] 2016-03-21 20:15
@perkyguy.  I have rebuild a complete board.  Same schematic, same chipset etc.  Works a treat actually.

However, I have the same issue.  The two Hex file do seem to operate differently.

Truly puzzled here.

**Comment by perkyguy** [comment] 2016-03-21 21:07
Thanks for linking the video, that helps immensely!

The video gave me a couple other things I'll try to do to reproduce the issue. Couple other things I might ask you to try while I'm working on it from my end
- It looks like you're using the 18**F**25K50 on your board, is that correct? If so, any chance you could get your hands on an 18**LF**25K50?
- Does the same thing happen with only one of the boards plugged in?
- Does the same  thing happen when you begin transfers from the zip file or your hard drive to the non-shipped board (as opposed to transferring from the shipped board)?

I will continue to look into why this could be happening and will keep you updated.

**Comment by Anobium** [comment] 2016-03-22 08:06
1. Re. 18LF25K50.  I have just requested some samples so this will take a day or two arrive.
2. Yes. Same thing happens when only one board plugged in.
3. Same from  zip file or your hard drive or a part of GCB programming (which is a file copy to the USB drive).

Can you send me the Bootloader compiled for the  18f25k50 device? I would like to rule this out.

**Comment by perkyguy** [comment] 2016-03-22 11:19
There is no bootloader for the Xpress board. This code is everything that gets programmed onto it.

Does this happen on the Xpress board, or just your other setup?

**Comment by Anobium** [comment] 2016-03-22 12:54
My shipped Express board does the following:  Remove USB cable, press S1 and reattach USB cable then instantly D1 is flashing Red.

I now have two replicas.  Both operate the same. Remove USB cable, press S1 and reattach USB cable then D1 is solid Red.  

The shipped board is operating in a different manner to the built ones in terms of the file handling still.  I have recompile the source and reloaded - no different.

Note. I am using the compiler is not optimised. Can you send me a version of the code that you have compiled from your compiler.  We need to rule of the optimisation your compiler may be giving you.  Please compile for 18f and the 18lf.  I can try both.

**Comment by perkyguy** [comment] 2016-03-23 18:23
Sorry, got confused there for a second. I was talking about my dev boards (none of which are able to reproduce your issue **yet**). I haven't been programming the shipped bootloader with my setups, and I've been using the free version of optimizations (I assume free unless someone says otherwise). 

The bootloader hex used on the shipped boards got pushed with the most recent commit (46f880059b38f5ee70c0a0c57063454fd51bdd17). This is the standard HID bootloader which comes with [MLA](http://www.microchip.com/mplab/microchip-libraries-for-applications). You can follow that link to get more information on the bootloader itself.

What I'm thinking is happening is a similar problem to what we experienced on earlier versions of the board. We were using the F device, but due to the operating voltage of the board we noticed a lot of internal latching of the internal USB regulator. The easiest way to fix this, and maintaining the rest of the design, was to simply move to the LF device. I'm thinking that your part is showing a marginal failure, but is able to recover, thus the shuddering/reinsert event. When you get the LF device, and try that out, let me know how things work. 

In the meantime, I'm still trying out different ways to reproduce your error.

**Comment by Anobium** [comment] 2016-03-23 18:30
So, may I check.  The design intent is for the file to remain the directory structure or not after programming?

**Comment by Anobium** [comment] 2016-03-23 18:38
I was thinking about the marginal failure.  I do not think this is what is happening.  Why? Same hardware (I have build two prototypes) and the shipped firmware works and the newly compiled does not.  How would one firmware be marginal and the other not?

**Comment by perkyguy** [comment] 2016-03-23 20:24
> The design intent is for the file to remain the directory structure or not after programming?

The file does not actually persist after programming, you can see this by just pressing the S1 button after you program a HEX file. The programmer does a soft detach but doesn't reinitialize anything afterwards. You can dig into the direct.c code also to see what's going under the hood a little more. The file appears to still be there due to the OS caching the file

> How would one firmware be marginal and the other not?

Good point. I still would like to see if going to an LF device helps at all.

You've tried this on another computer, right? Also, have you only been reprogramming the prototypes you built up? Or have you tried reprogramming the shipped Xpress board?

**Comment by Anobium** [comment] 2016-03-23 22:00
Then code shipped is not operating as expected.

A test we should carry out.
Do you have a production Xpress board? If yes, I will send you the HEX from my production board and we can try if you have the same issue.  Do you have a production board?

**Comment by perkyguy** [comment] 2016-03-23 23:01
I might have confused things a little. What should happen (and does on a shipped board that I have and the one that you showed in your video)
1. Plug in USB
   - Green LED comes on
   - XPRESS mass storage device (MSD) appears and contains
     - readme.htm
2. Copy HEX File over to XPRESS MSD
   - Red LED comes on while programming
   - Green LED comes on after programming finishes
   - XPRESS MSD contains
     - readme.htm
     - HEX file
   - Target begins executing after programming finishes
3. S1 Button pressed
   - XPRESS MSD detaches
   - Target stops executing
4. S1 button released
   - XPRESS MSD appears and contains
     - readme.htm
   - Target begins executing

This is the behavior I saw in your video, is this incorrect?

**Comment by Anobium** [comment] 2016-03-24 12:15
See attached.  I did not have time to learn this markup.  I could not get the numbers to restart.  

:-)
[Modified process for the shipped code.txt](https://github.com/MicrochipTech/XPRESS-Loader/files/187802/Modified.process.for.the.shipped.code.txt)

**Comment by perkyguy** [comment] 2016-03-24 13:39
It seems like you misunderstood why I brought up the S1 button HEX file thing. I brought it up to illustrate the point that the HEX file doesn't actually exist in the "msd" ever. The operating system caches it because it assumes a msd won't do device side changes and will act simply as a storage device. So some derivation from the steps I had laid out is most likely due to the operating system acting slightly differently. 

Did you try this on another computer?

**Comment by Anobium** [comment] 2016-03-24 13:41
I can try another computer. A good idea.  I will try and I will respond.

It still brings us back to the original issue. When I try the GitHub code...things operate differently.

**Comment by perkyguy** [comment] 2016-05-12 23:44
@Anobium , were you ever able to get this working? Did the issue go away with the LF device?

**Comment by Anobium** [comment] 2016-05-16 13:04
Same issues with the LF device.

I can confirm that my friend in Australia (I am in the UK) has the same issues.

Another comment: This cannot be same release as the shipped code in the device.  Why? the README.HTM in the shipped device works... it redirects as expected. The project build does not work.  This is the same of the F and the LF device.  I cannot think these are the same release levels.

Thank you.

**Closed as completed** 2016-12-28 14:34 UTC
